name: "Template for install OpenVPN"

inputs:
  OVPN_CONFIG_FILE:
    description: "OVPN Config File"
    required: true
  OVPN_CERT_PASS::
    description: "OVPN Cert Pass"
    required: true
runs:
  using: "composite"
  steps:
      - name: Installl OpenVPN
        shell: bash
        run: |
          sudo apt update > /dev/null
          sudo apt install openvpn -y > /dev/null
      - name: Config VPN
        shell: bash
        run: |
          echo "${{ inputs.OVPN_CONFIG_FILE }}" > cicd.ovpn  
          echo "${{ inputs.OVPN_CERT_PASS }}" > vpn_pass.txt        
      - name: connect on VPN
        shell: bash
        run: | 
         sudo openvpn --config cicd.ovpn --askpass vpn_pass.txt --daemon
      - name: Waiting VPN connect
        shell: bash
        run: | 
         sleep 5
      - name: Checking connection VPN
        shell: bash
        run: |
          found_int_count=$(ip address | grep -o " tun" | wc -l)
          if [ $found_int_count -eq 0 ]; then
            echo "ERRO: Interface VPN not find!"
            exit 1
          fi
